format = """
$directory$git_branch$git_status$python$nodejs$rust$golang
$character
"""

[directory]
style = "bold fg:green"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold fg:yellow"

[git_status]
style = "fg:cyan"

[python]
symbol = ""
style = "fg:green"
format = ' [$symbol$version]($style)'

[golang]
symbol = "󰟓"
style = "fg:blue"
format = ' [$symbol$version]($style)'

[character]
success_symbol = "[❯](bold fg:green)"
error_symbol = "[❯](bold fg:red)"
