# mezora theme - sauce for macchina cli

separator="Ω"
separator_color="orange"
key_color="cyan"
prefer_small_ascii = true

[palette]
type="Dark"
visible=true
glyph=" ⬤ "

[box]
title=" x-wing "
border="double"
visible=true

[bar]
glyph="▮ "
hide_delimiters=true
visible=true

[randomize]
key_color=false
separator_color=false

[custom_ascii]
color="orange"
path="/Users/santtuniskanen/.config/macchina/themes/ascii/xwing.txt"

[keys]
host="⌂host"
kernel="☸ kernel"
distro=" distro"
packages=" packages"
terminal=" terminal"
shell=" shell"
cpu=" cpu"
cpu_load=" cpu"
memory=" memory"
battery="☇ battery"

